{"uid":"357793ddef3b3541","name":"capmcAPIGetXnameStatus via Redfish","fullName":"api.1-non-disruptive.test_get_xname_status.tavern#capmcAPIGetXnameStatus via Redfish","historyId":"31b0f5897a5f578325039da57cc8cc21","time":{"start":1678221183805,"stop":1678221183903,"duration":98},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"passed","steps":[{"name":"Stage 0: capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)","time":{"start":1678221183811,"stop":1678221183856,"duration":45},"status":"passed","steps":[],"attachments":[{"uid":"4746a3752dcdc86a","name":"stage_yaml","source":"4746a3752dcdc86a.yaml","type":"application/yaml","size":478},{"uid":"a1ef416f61edd89b","name":"rest_request","source":"a1ef416f61edd89b.yaml","type":"application/yaml","size":155},{"uid":"c381a7a85ee24b6","name":"rest_response","source":"c381a7a85ee24b6.yaml","type":"application/yaml","size":974}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 1: capmcAPIGetXnameStatusPOST - Validate response has valid fields (Redfish)","time":{"start":1678221183856,"stop":1678221183902,"duration":46},"status":"passed","steps":[],"attachments":[{"uid":"74091fbefb7ac21b","name":"stage_yaml","source":"74091fbefb7ac21b.yaml","type":"application/yaml","size":1149},{"uid":"697cffad2bd9ca1d","name":"rest_request","source":"697cffad2bd9ca1d.yaml","type":"application/yaml","size":155},{"uid":"5d5f5c34ba08361c","name":"rest_response","source":"5d5f5c34ba08361c.yaml","type":"application/yaml","size":974}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true}],"attachments":[],"parameters":[],"stepsCount":2,"attachmentsCount":6,"shouldDisplayMessage":false,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"cray-capmc-hmth-test"},{"name":"suite","value":"1-non-disruptive"},{"name":"host","value":"09b81b449698"},{"name":"thread","value":"8-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"api.1-non-disruptive.test_get_xname_status.tavern"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"history":{"statistic":{"failed":14,"broken":0,"skipped":0,"passed":12,"unknown":0,"total":26},"items":[{"uid":"de8a5d11c2136f07","status":"passed","time":{"start":1678217490801,"stop":1678217490904,"duration":103}},{"uid":"e1100f57d4c5ba9c","status":"passed","time":{"start":1678215944235,"stop":1678215944365,"duration":130}},{"uid":"5e435bd2c6d85611","status":"passed","time":{"start":1678212657270,"stop":1678212657368,"duration":98}},{"uid":"2c3f41f39e9f6429","status":"passed","time":{"start":1674679858076,"stop":1674679858169,"duration":93}},{"uid":"e4d0a36ad5cb8997","status":"passed","time":{"start":1674664355829,"stop":1674664355940,"duration":111}},{"uid":"11aa13563449261","status":"passed","time":{"start":1674514451811,"stop":1674514451903,"duration":92}},{"uid":"4c1ecdd97ddd49d5","status":"passed","time":{"start":1674504519801,"stop":1674504519939,"duration":138}},{"uid":"bebe806e83919e2e","status":"passed","time":{"start":1674499308684,"stop":1674499308778,"duration":94}},{"uid":"7baedd277f8c8207","status":"passed","time":{"start":1674256689378,"stop":1674256689479,"duration":101}},{"uid":"1571559fed19f503","status":"passed","time":{"start":1674254067596,"stop":1674254067693,"duration":97}},{"uid":"3e047299dbd8f866","status":"passed","time":{"start":1674244981225,"stop":1674244981351,"duration":126}},{"uid":"5b88ff069f6d841d","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7f2f3a4604c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674231180452,"stop":1674231185493,"duration":5041}},{"uid":"3a1baf8028084067","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7f5d6d61b4c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674168293302,"stop":1674168298336,"duration":5034}},{"uid":"b596fca4a26b3924","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7fdefd5fa4c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674147100576,"stop":1674147105613,"duration":5037}},{"uid":"9d6af3523a14edcf","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7fbe088cb4c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674146086245,"stop":1674146091295,"duration":5050}},{"uid":"be0f6ac3a36bf421","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7f2cfdada4c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674145039445,"stop":1674145044494,"duration":5049}},{"uid":"26636cf5a858278c","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7fc5a7b674c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674142507198,"stop":1674142512234,"duration":5036}},{"uid":"dfbcf58729291804","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7ffaf711c4c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674141924226,"stop":1674141929260,"duration":5034}},{"uid":"19f39dba72d61760","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7f324e44b4c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674080230076,"stop":1674080235121,"duration":5045}},{"uid":"66038a3e74635f6b","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'capmcAPIGetXnameStatusPOST - Validate proper number of json fields (Redfish)' failed:\n- Error calling validate function '<function validate_content at 0x7fcb0168a4c0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 181, in validate_content\n        actual_validation(\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/jmesutils.py\", line 87, in actual_validation\n        raise exceptions.JMESError(\n    tavern.util.exceptions.JMESError: Validation 'length(keys(@)) gt 2' (2 gt 2) failed!","time":{"start":1674074961653,"stop":1674074966703,"duration":5050}}]},"tags":[]},"source":"357793ddef3b3541.json","parameterValues":[]}