{"uid":"447edaa04241bee3","name":"hsmAPIinventoryHardwareDisruptive","fullName":"api.2-disruptive.test_hardware.tavern#hsmAPIinventoryHardwareDisruptive","historyId":"835ff18518ce742b155f9cf4039900b3","time":{"start":1678225228817,"stop":1678225231774,"duration":2957},"status":"failed","statusMessage":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f5c1b7125e0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/24'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/25'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/44'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/46'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/70'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/73'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/541'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/543'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/548'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/549'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","statusTrace":"Format variables:\n  hsm_base_url = 'http://cray-smd:27779'\n  verify = 'False'\n\nSource test stage (line 2205):\n  - name: hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.\n    request:\n      url: \"{hsm_base_url}/hsm/v2/Inventory/Hardware\"\n      method: GET\n      verify: !bool \"{verify}\"\n    response:\n      status_code: 200\n      verify_response_with:\n        function: tavern.testutils.helpers:validate_pykwalify\n        extra_kwargs:\n          schema:\n            type: seq\n            required: True\n            matching: all\n            sequence:\n              - type: map\n                required: True\n\n                allowempty: True\n                mapping:\n                  ID:\n                    type: str\n                    required: True\n                  Type:\n                    type: str\n                    required: True\n                  Ordinal:\n                    type: int\n                    required: True\n                  Status:\n                    type: str\n                    required: True\n                  HWInventoryByLocationType:\n                    type: str\n                    required: True\n                  PopulatedFRU:\n                    type: map\n                    required: True\n\n                    allowempty: True\n                    mapping:\n                      FRUID:\n                        type: str\n                        required: True\n                      Type:\n                        type: str\n                        required: True\n                      Subtype:\n                        type: str\n                        required: True\n\n\n\n\nFormatted stage:\n  name: hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using\n    GET.\n  request:\n    method: GET\n    url: 'http://cray-smd:27779/hsm/v2/Inventory/Hardware'\n    verify: !bool 'False'\n  response:\n    status_code: 200\n    verify_response_with:\n      extra_kwargs:\n        schema:\n          matching: all\n          required: true\n          sequence:\n          - allowempty: true\n            mapping:\n              HWInventoryByLocationType:\n                required: true\n                type: str\n              ID:\n                required: true\n                type: str\n              Ordinal:\n                required: true\n                type: int\n              PopulatedFRU:\n                allowempty: true\n                mapping:\n                  FRUID:\n                    required: true\n                    type: str\n                  Subtype:\n                    required: true\n                    type: str\n                  Type:\n                    required: true\n                    type: str\n                required: true\n                type: map\n              Status:\n                required: true\n                type: str\n              Type:\n                required: true\n                type: str\n            required: true\n            type: map\n          type: seq\n      function: tavern.testutils.helpers:validate_pykwalify\n\nErrors:\nE   tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n    - Error calling validate function '<function validate_pykwalify at 0x7f5c1b7125e0>':\n        Traceback (most recent call last):\n          File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n            verifier.validate()\n          File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n            raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n        pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n         - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/24'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/25'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/44'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/46'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/70'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/73'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/541'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/543'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/548'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/549'.: Path: '/'>\n    \n        The above exception was the direct cause of the following exception:\n    \n        Traceback (most recent call last):\n          File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n            vf(response)\n          File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n            result = func(response, *args, **kwargs)\n          File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n            verify_generic(to_verify, schema)\n          File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n            raise BadSchemaError() from e\n        tavern.util.exceptions.BadSchemaError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f5c1b7125e0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/24'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/25'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/44'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/46'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/70'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/73'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/541'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/543'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/548'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/549'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","statusTrace":"Format variables:\n  hsm_base_url = 'http://cray-smd:27779'\n  verify = 'False'\n\nSource test stage (line 2205):\n  - name: hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.\n    request:\n      url: \"{hsm_base_url}/hsm/v2/Inventory/Hardware\"\n      method: GET\n      verify: !bool \"{verify}\"\n    response:\n      status_code: 200\n      verify_response_with:\n        function: tavern.testutils.helpers:validate_pykwalify\n        extra_kwargs:\n          schema:\n            type: seq\n            required: True\n            matching: all\n            sequence:\n              - type: map\n                required: True\n\n                allowempty: True\n                mapping:\n                  ID:\n                    type: str\n                    required: True\n                  Type:\n                    type: str\n                    required: True\n                  Ordinal:\n                    type: int\n                    required: True\n                  Status:\n                    type: str\n                    required: True\n                  HWInventoryByLocationType:\n                    type: str\n                    required: True\n                  PopulatedFRU:\n                    type: map\n                    required: True\n\n                    allowempty: True\n                    mapping:\n                      FRUID:\n                        type: str\n                        required: True\n                      Type:\n                        type: str\n                        required: True\n                      Subtype:\n                        type: str\n                        required: True\n\n\n\n\nFormatted stage:\n  name: hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using\n    GET.\n  request:\n    method: GET\n    url: 'http://cray-smd:27779/hsm/v2/Inventory/Hardware'\n    verify: !bool 'False'\n  response:\n    status_code: 200\n    verify_response_with:\n      extra_kwargs:\n        schema:\n          matching: all\n          required: true\n          sequence:\n          - allowempty: true\n            mapping:\n              HWInventoryByLocationType:\n                required: true\n                type: str\n              ID:\n                required: true\n                type: str\n              Ordinal:\n                required: true\n                type: int\n              PopulatedFRU:\n                allowempty: true\n                mapping:\n                  FRUID:\n                    required: true\n                    type: str\n                  Subtype:\n                    required: true\n                    type: str\n                  Type:\n                    required: true\n                    type: str\n                required: true\n                type: map\n              Status:\n                required: true\n                type: str\n              Type:\n                required: true\n                type: str\n            required: true\n            type: map\n          type: seq\n      function: tavern.testutils.helpers:validate_pykwalify\n\nErrors:\nE   tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n    - Error calling validate function '<function validate_pykwalify at 0x7f5c1b7125e0>':\n        Traceback (most recent call last):\n          File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n            verifier.validate()\n          File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n            raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n        pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n         - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/24'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/25'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/44'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/46'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/70'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/73'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/541'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/543'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/548'.\n         - Cannot find required key 'PopulatedFRU'. Path: '/549'.: Path: '/'>\n    \n        The above exception was the direct cause of the following exception:\n    \n        Traceback (most recent call last):\n          File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n            vf(response)\n          File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n            result = func(response, *args, **kwargs)\n          File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n            verify_generic(to_verify, schema)\n          File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n            raise BadSchemaError() from e\n        tavern.util.exceptions.BadSchemaError","steps":[{"name":"Stage 0: hsmAPIinventoryHardwarePOSTcmmRectifier - Create a CMMRectifier Hardware Inventory entry using POST.","time":{"start":1678225228844,"stop":1678225228869,"duration":25},"status":"passed","steps":[],"attachments":[{"uid":"5e12c766873f2abc","name":"stage_yaml","source":"5e12c766873f2abc.yaml","type":"application/yaml","size":1257},{"uid":"b511498b99141dc4","name":"rest_request","source":"b511498b99141dc4.yaml","type":"application/yaml","size":779},{"uid":"2c93b97567b28374","name":"rest_response","source":"2c93b97567b28374.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 1: hsmAPIinventoryHardwareXnameGETcmmRectifier - Retrieve a CMMRectifier Hardware Inventory entry by xname using GET.","time":{"start":1678225228869,"stop":1678225228886,"duration":17},"status":"passed","steps":[],"attachments":[{"uid":"d7ebdeb833af6a91","name":"stage_yaml","source":"d7ebdeb833af6a91.yaml","type":"application/yaml","size":3659},{"uid":"15dd495f75442f2","name":"rest_request","source":"15dd495f75442f2.yaml","type":"application/yaml","size":138},{"uid":"f0bacd5c502bd08a","name":"rest_response","source":"f0bacd5c502bd08a.yaml","type":"application/yaml","size":741}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 2: hsmAPIinventoryHardwarePOSTchassis - Create a Chassis Hardware Inventory entry using POST.","time":{"start":1678225228887,"stop":1678225228904,"duration":17},"status":"passed","steps":[],"attachments":[{"uid":"c09643a4cdd3788b","name":"stage_yaml","source":"c09643a4cdd3788b.yaml","type":"application/yaml","size":1204},{"uid":"fc846db23206c33e","name":"rest_request","source":"fc846db23206c33e.yaml","type":"application/yaml","size":731},{"uid":"788999fc23124a4b","name":"rest_response","source":"788999fc23124a4b.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 3: hsmAPIinventoryHardwareXnameGETchassis - Retrieve a Chassis Hardware Inventory entry by xname using GET.","time":{"start":1678225228904,"stop":1678225228920,"duration":16},"status":"passed","steps":[],"attachments":[{"uid":"d57d5cecfe56a3ae","name":"stage_yaml","source":"d57d5cecfe56a3ae.yaml","type":"application/yaml","size":3706},{"uid":"c87512357d6cd2bb","name":"rest_request","source":"c87512357d6cd2bb.yaml","type":"application/yaml","size":136},{"uid":"18458524277634ef","name":"rest_response","source":"18458524277634ef.yaml","type":"application/yaml","size":691}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 4: hsmAPIinventoryHardwarePOSTcomputeModule - Create a ComputeModule Hardware Inventory entry using POST.","time":{"start":1678225228920,"stop":1678225228937,"duration":17},"status":"passed","steps":[],"attachments":[{"uid":"f7abfb0cb157af10","name":"stage_yaml","source":"f7abfb0cb157af10.yaml","type":"application/yaml","size":1201},{"uid":"f6bbd4bd4ef9592","name":"rest_request","source":"f6bbd4bd4ef9592.yaml","type":"application/yaml","size":722},{"uid":"ec4e56b9edb46bc6","name":"rest_response","source":"ec4e56b9edb46bc6.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 5: hsmAPIinventoryHardwareXnameGETcomputeModule - Retrieve a ComputeModule Hardware Inventory entry by xname using GET.","time":{"start":1678225228938,"stop":1678225228955,"duration":17},"status":"passed","steps":[],"attachments":[{"uid":"605f6c0120d249d7","name":"stage_yaml","source":"605f6c0120d249d7.yaml","type":"application/yaml","size":3705},{"uid":"ac5447c690d9ff9f","name":"rest_request","source":"ac5447c690d9ff9f.yaml","type":"application/yaml","size":138},{"uid":"982ab200ba86a734","name":"rest_response","source":"982ab200ba86a734.yaml","type":"application/yaml","size":682}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 6: hsmAPIinventoryHardwarePOSThsnBoard - Create an HSNBoard Hardware Inventory entry using POST.","time":{"start":1678225228955,"stop":1678225228974,"duration":19},"status":"passed","steps":[],"attachments":[{"uid":"53fa5de80750ca64","name":"stage_yaml","source":"53fa5de80750ca64.yaml","type":"application/yaml","size":1268},{"uid":"1de47189ba54da23","name":"rest_request","source":"1de47189ba54da23.yaml","type":"application/yaml","size":792},{"uid":"7287d64deb051779","name":"rest_response","source":"7287d64deb051779.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 7: hsmAPIinventoryHardwareXnameGEThsnBoard - Retrieve an HSNBoard Hardware Inventory entry by xname using GET.","time":{"start":1678225228974,"stop":1678225228991,"duration":17},"status":"passed","steps":[],"attachments":[{"uid":"7d010a39677f0159","name":"stage_yaml","source":"7d010a39677f0159.yaml","type":"application/yaml","size":3774},{"uid":"b07136b555ca3ede","name":"rest_request","source":"b07136b555ca3ede.yaml","type":"application/yaml","size":140},{"uid":"267ee1b192ae7d1a","name":"rest_response","source":"267ee1b192ae7d1a.yaml","type":"application/yaml","size":752}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 8: hsmAPIinventoryHardwarePOSTmemory - Create a Memory Hardware Inventory entry using POST.","time":{"start":1678225228991,"stop":1678225229011,"duration":20},"status":"passed","steps":[],"attachments":[{"uid":"a30891d92f4ee4ac","name":"stage_yaml","source":"a30891d92f4ee4ac.yaml","type":"application/yaml","size":1405},{"uid":"503c932f1fc50592","name":"rest_request","source":"503c932f1fc50592.yaml","type":"application/yaml","size":993},{"uid":"95b4140ee49282c0","name":"rest_response","source":"95b4140ee49282c0.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 9: hsmAPIinventoryHardwareXnameGETmemory - Retrieve a Memory Hardware Inventory entry by xname using GET.","time":{"start":1678225229012,"stop":1678225229032,"duration":20},"status":"passed","steps":[],"attachments":[{"uid":"d51025afb6129745","name":"stage_yaml","source":"d51025afb6129745.yaml","type":"application/yaml","size":5172},{"uid":"4e198a7ee587a57c","name":"rest_request","source":"4e198a7ee587a57c.yaml","type":"application/yaml","size":144},{"uid":"8d535161c5db1a17","name":"rest_response","source":"8d535161c5db1a17.yaml","type":"application/yaml","size":935}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 10: hsmAPIinventoryHardwarePOSTnodeBMC - Create a NodeBMC Hardware Inventory entry using POST.","time":{"start":1678225229032,"stop":1678225229049,"duration":17},"status":"passed","steps":[],"attachments":[{"uid":"3620b4a71148c222","name":"stage_yaml","source":"3620b4a71148c222.yaml","type":"application/yaml","size":1220},{"uid":"f09b34831b058497","name":"rest_request","source":"f09b34831b058497.yaml","type":"application/yaml","size":749},{"uid":"12a20edbc3941c4d","name":"rest_response","source":"12a20edbc3941c4d.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 11: hsmAPIinventoryHardwareXnameGETnodeBMC - Retrieve a NodeBMC Hardware Inventory entry by xname using GET.","time":{"start":1678225229050,"stop":1678225229068,"duration":18},"status":"passed","steps":[],"attachments":[{"uid":"585fcb5e26d31056","name":"stage_yaml","source":"585fcb5e26d31056.yaml","type":"application/yaml","size":3686},{"uid":"a56f0035f4633aec","name":"rest_request","source":"a56f0035f4633aec.yaml","type":"application/yaml","size":140},{"uid":"1acfbc45e5ca433f","name":"rest_response","source":"1acfbc45e5ca433f.yaml","type":"application/yaml","size":709}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 12: hsmAPIinventoryHardwarePOSTnodeEnclosure - Create a NodeEnclosure Hardware Inventory entry using POST.","time":{"start":1678225229069,"stop":1678225229089,"duration":20},"status":"passed","steps":[],"attachments":[{"uid":"ee523c6cd74ed637","name":"stage_yaml","source":"ee523c6cd74ed637.yaml","type":"application/yaml","size":1262},{"uid":"f20cb48894a91be2","name":"rest_request","source":"f20cb48894a91be2.yaml","type":"application/yaml","size":777},{"uid":"f20528480d234fc2","name":"rest_response","source":"f20528480d234fc2.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 13: hsmAPIinventoryHardwareXnameGETnodeEnclosure - Retrieve a NodeEnclosure Hardware Inventory entry by xname using GET.","time":{"start":1678225229089,"stop":1678225229106,"duration":17},"status":"passed","steps":[],"attachments":[{"uid":"ebf5cd58c40fcd68","name":"stage_yaml","source":"ebf5cd58c40fcd68.yaml","type":"application/yaml","size":3768},{"uid":"d6ddbf9cda406b58","name":"rest_request","source":"d6ddbf9cda406b58.yaml","type":"application/yaml","size":140},{"uid":"c316f4f3ba9bafae","name":"rest_response","source":"c316f4f3ba9bafae.yaml","type":"application/yaml","size":737}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 14: hsmAPIinventoryHardwarePOSTnodeHsnNic - Create a NodeHsnNic Hardware Inventory entry using POST.","time":{"start":1678225229106,"stop":1678225229125,"duration":19},"status":"passed","steps":[],"attachments":[{"uid":"44b35d8ae8a14c3d","name":"stage_yaml","source":"44b35d8ae8a14c3d.yaml","type":"application/yaml","size":1198},{"uid":"105c8098f9232f67","name":"rest_request","source":"105c8098f9232f67.yaml","type":"application/yaml","size":697},{"uid":"f45e756c9a23ebef","name":"rest_response","source":"f45e756c9a23ebef.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 15: hsmAPIinventoryHardwareXnameGETnodeHsnNic - Retrieve a NodeHsnNic Hardware Inventory entry by xname using GET.","time":{"start":1678225229126,"stop":1678225229141,"duration":15},"status":"passed","steps":[],"attachments":[{"uid":"c887cfd46b011f4a","name":"stage_yaml","source":"c887cfd46b011f4a.yaml","type":"application/yaml","size":3160},{"uid":"37a2fc1a3cfb850a","name":"rest_request","source":"37a2fc1a3cfb850a.yaml","type":"application/yaml","size":144},{"uid":"c2840b765616bfe4","name":"rest_response","source":"c2840b765616bfe4.yaml","type":"application/yaml","size":665}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 16: hsmAPIinventoryHardwarePOSTnodeCreate - Create a Node Hardware Inventory entry using POST.","time":{"start":1678225229141,"stop":1678225229160,"duration":19},"status":"passed","steps":[],"attachments":[{"uid":"1db2e0754f7793f9","name":"stage_yaml","source":"1db2e0754f7793f9.yaml","type":"application/yaml","size":1354},{"uid":"ed3b97a162b1ebc1","name":"rest_request","source":"ed3b97a162b1ebc1.yaml","type":"application/yaml","size":918},{"uid":"64a10a7ad286d089","name":"rest_response","source":"64a10a7ad286d089.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 17: hsmAPIinventoryHardwareXnameGETnodeCreate - Retrieve a Node Hardware Inventory entry by xname using GET.","time":{"start":1678225229160,"stop":1678225229184,"duration":24},"status":"passed","steps":[],"attachments":[{"uid":"704709bcd619851d","name":"stage_yaml","source":"704709bcd619851d.yaml","type":"application/yaml","size":4772},{"uid":"a9914c85189ae023","name":"rest_request","source":"a9914c85189ae023.yaml","type":"application/yaml","size":142},{"uid":"3f2fa55af405d4e1","name":"rest_response","source":"3f2fa55af405d4e1.yaml","type":"application/yaml","size":862}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 18: hsmAPIinventoryHardwarePOSTnodeUpdate - Update a Node Hardware Inventory entry using POST.","time":{"start":1678225229185,"stop":1678225229204,"duration":19},"status":"passed","steps":[],"attachments":[{"uid":"72f489a6b72c20ba","name":"stage_yaml","source":"72f489a6b72c20ba.yaml","type":"application/yaml","size":1393},{"uid":"42321412d3284452","name":"rest_request","source":"42321412d3284452.yaml","type":"application/yaml","size":953},{"uid":"ed692bba2c3e0fa1","name":"rest_response","source":"ed692bba2c3e0fa1.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 19: hsmAPIinventoryHardwareXnameGETnodeUpdate - Retrieve an updated Node Hardware Inventory entry by xname using GET.","time":{"start":1678225229204,"stop":1678225229222,"duration":18},"status":"passed","steps":[],"attachments":[{"uid":"ac8a0d96473d2531","name":"stage_yaml","source":"ac8a0d96473d2531.yaml","type":"application/yaml","size":4820},{"uid":"4d4bf0f6d5cd43d4","name":"rest_request","source":"4d4bf0f6d5cd43d4.yaml","type":"application/yaml","size":142},{"uid":"5349e8ab69d968b0","name":"rest_response","source":"5349e8ab69d968b0.yaml","type":"application/yaml","size":897}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 20: hsmAPIinventoryHardwarePOSTprocessor - Create a Processor Hardware Inventory entry using POST.","time":{"start":1678225229223,"stop":1678225229241,"duration":18},"status":"passed","steps":[],"attachments":[{"uid":"4021f78d812d26a7","name":"stage_yaml","source":"4021f78d812d26a7.yaml","type":"application/yaml","size":1505},{"uid":"df724ed072a388a9","name":"rest_request","source":"df724ed072a388a9.yaml","type":"application/yaml","size":1115},{"uid":"3ccbf3b8bb32a5e9","name":"rest_response","source":"3ccbf3b8bb32a5e9.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 21: hsmAPIinventoryHardwareXnameGETprocessor - Retrieve a Processor Hardware Inventory entry by xname using GET.","time":{"start":1678225229242,"stop":1678225229261,"duration":19},"status":"passed","steps":[],"attachments":[{"uid":"c8b71b9e018cfb27","name":"stage_yaml","source":"c8b71b9e018cfb27.yaml","type":"application/yaml","size":5555},{"uid":"2f1d968cd82ecb87","name":"rest_request","source":"2f1d968cd82ecb87.yaml","type":"application/yaml","size":144},{"uid":"9ead580acbc332a9","name":"rest_response","source":"9ead580acbc332a9.yaml","type":"application/yaml","size":1053}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 22: hsmAPIinventoryHardwarePOSTrouterBMC - Create a RouterBMC Hardware Inventory entry using POST.","time":{"start":1678225229261,"stop":1678225229279,"duration":18},"status":"passed","steps":[],"attachments":[{"uid":"f1707624672436c3","name":"stage_yaml","source":"f1707624672436c3.yaml","type":"application/yaml","size":1226},{"uid":"464718aaf171e291","name":"rest_request","source":"464718aaf171e291.yaml","type":"application/yaml","size":753},{"uid":"79dc9bf3a62cd5ac","name":"rest_response","source":"79dc9bf3a62cd5ac.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 23: hsmAPIinventoryHardwareXnameGETrouterBMC - Retrieve a RouterBMC Hardware Inventory entry by xname using GET.","time":{"start":1678225229280,"stop":1678225229291,"duration":11},"status":"passed","steps":[],"attachments":[{"uid":"f7f0ddf2f5d15309","name":"stage_yaml","source":"f7f0ddf2f5d15309.yaml","type":"application/yaml","size":272},{"uid":"4600425d2a77345d","name":"rest_request","source":"4600425d2a77345d.yaml","type":"application/yaml","size":140},{"uid":"58bc9195299ff8ee","name":"rest_response","source":"58bc9195299ff8ee.yaml","type":"application/yaml","size":713}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 24: hsmAPIinventoryHardwarePOSTrouterModule - Create a RouterModule Hardware Inventory entry using POST.","time":{"start":1678225229292,"stop":1678225229309,"duration":17},"status":"passed","steps":[],"attachments":[{"uid":"3801161e3cb37bc2","name":"stage_yaml","source":"3801161e3cb37bc2.yaml","type":"application/yaml","size":1193},{"uid":"eeef56ef966e1b32","name":"rest_request","source":"eeef56ef966e1b32.yaml","type":"application/yaml","size":716},{"uid":"d43f66441da35055","name":"rest_response","source":"d43f66441da35055.yaml","type":"application/yaml","size":191}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 25: hsmAPIinventoryHardwareXnameGETrouterModule - Retrieve a RouterModule Hardware Inventory entry by xname using GET.","time":{"start":1678225229310,"stop":1678225229326,"duration":16},"status":"passed","steps":[],"attachments":[{"uid":"bcb091dbafebae26","name":"stage_yaml","source":"bcb091dbafebae26.yaml","type":"application/yaml","size":3697},{"uid":"60473f28cf36efb7","name":"rest_request","source":"60473f28cf36efb7.yaml","type":"application/yaml","size":138},{"uid":"f733d01946fa9dc7","name":"rest_response","source":"f733d01946fa9dc7.yaml","type":"application/yaml","size":676}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":false,"hasContent":true},{"name":"Stage 26: hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.","time":{"start":1678225229326,"stop":1678225231773,"duration":2447},"status":"failed","statusMessage":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f5c1b7125e0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/24'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/25'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/44'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/46'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/70'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/73'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/541'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/543'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/548'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/549'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError\n\n","statusTrace":"  File \"/usr/lib/python3.9/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"/usr/lib/python3.9/site-packages/tavern/util/retry.py\", line 31, in wrapped\n    res = fn(*args, **kwargs)\n  File \"/usr/lib/python3.9/site-packages/tavern/core.py\", line 270, in run_stage\n    saved = v.verify(response)\n  File \"/usr/lib/python3.9/site-packages/tavern/_plugins/rest/response.py\", line 201, in verify\n    raise exceptions.TestFailError(\n","steps":[],"attachments":[{"uid":"f5055c7e46be24b3","name":"stage_yaml","source":"f5055c7e46be24b3.yaml","type":"application/yaml","size":1437},{"uid":"3c3c4641b7ec9563","name":"rest_request","source":"3c3c4641b7ec9563.yaml","type":"application/yaml","size":128},{"uid":"fce434ea5cffbc6d","name":"rest_response","source":"fce434ea5cffbc6d.yaml","type":"application/yaml","size":579275}],"parameters":[],"stepsCount":0,"attachmentsCount":3,"shouldDisplayMessage":true,"hasContent":true}],"attachments":[{"uid":"62548d2f34ecb56","name":"error_output","source":"62548d2f34ecb56.attach","type":"text/plain","size":6713},{"uid":"7593b2611e3f1052","name":"log","source":"7593b2611e3f1052.txt","type":"text/plain","size":582659}],"parameters":[],"stepsCount":27,"attachmentsCount":83,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"cray-smd-hmth-test"},{"name":"suite","value":"2-disruptive"},{"name":"host","value":"d36388e304b2"},{"name":"thread","value":"8-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"api.2-disruptive.test_hardware.tavern"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":13,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":13},"items":[{"uid":"25639d16b8b74232","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fcfafaf75e0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/27'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/42'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/43'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/44'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/46'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/57'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/61'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/62'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/64'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/70'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/73'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/660'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/662'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/766'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/767'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1678221209318,"stop":1678221212136,"duration":2818}},{"uid":"ec8638fc54b35eb7","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f11f298a5e0>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/23'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/42'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/43'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/45'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/46'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/54'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/58'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/73'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/603'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/605'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/613'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/617'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1678217520187,"stop":1678217523055,"duration":2868}},{"uid":"7445331cb2d0bd8b","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f9a6d52f670>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/25'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/26'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/43'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/44'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/46'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/58'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/69'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/70'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/73'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/530'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/533'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/539'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/540'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1676400974254,"stop":1676400978144,"duration":3890}},{"uid":"2383bb3861f3d39","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fe894082670>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/23'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/44'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/45'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/52'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/58'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/62'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/70'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/71'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/541'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/546'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/551'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/552'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1676325739720,"stop":1676325742528,"duration":2808}},{"uid":"89b86da69efbeec9","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f8dbb859670>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/25'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/26'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/43'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/45'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/52'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/57'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/61'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/62'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/70'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/71'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/618'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/620'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/622'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/629'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1674515660106,"stop":1674515662918,"duration":2812}},{"uid":"d95fca93188b10de","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fea16d93670>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/17'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/23'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/42'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/45'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/46'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/57'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/58'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/61'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/62'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/64'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/69'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/302'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/312'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/315'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/316'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1674505807629,"stop":1674505810445,"duration":2816}},{"uid":"de960c7c1faa773e","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7fd84b340670>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/11'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/23'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/28'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/42'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/44'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/45'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/58'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/61'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/63'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/64'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/65'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/612'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/613'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/616'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/617'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1674500436067,"stop":1674500438913,"duration":2846}},{"uid":"6d77f94a9a473916","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f1abc08e670>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/10'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/20'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/26'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/27'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/42'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/44'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/55'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/56'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/57'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/62'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/64'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/70'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/71'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/72'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/597'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/607'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/611'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/612'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1674257930093,"stop":1674257932940,"duration":2847}},{"uid":"651bafad9414cf1f","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f875bc8b670>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/5'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/6'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/7'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/8'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/9'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/12'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/13'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/14'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/15'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/16'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/18'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/19'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/25'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/26'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/42'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/45'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/46'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/47'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/50'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/51'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/53'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/57'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/61'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/64'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/66'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/67'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/68'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/531'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/538'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/548'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/551'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1674255397554,"stop":1674255400958,"duration":3404}},{"uid":"251d87674b514bd7","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f6a576a8670>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/84'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/91'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/92'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/93'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1674080279001,"stop":1674080279898,"duration":897}},{"uid":"34f61f14cd42b8a1","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f08457c6670>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/48'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/49'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/59'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/60'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1674074993415,"stop":1674074994414,"duration":999}},{"uid":"dd043e4f44e3dd3","status":"failed","statusDetails":"tavern.util.exceptions.TestFailError: Test 'hsmAPIinventoryHardwareGET - Retrieve multiple Hardware Inventory entries using GET.' failed:\n- Error calling validate function '<function validate_pykwalify at 0x7f3b1a200670>':\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 106, in verify_generic\n        verifier.validate()\n      File \"/usr/lib/python3.9/site-packages/pykwalify/core.py\", line 194, in validate\n        raise SchemaError(u\"Schema validation failed:\\n - {error_msg}.\".format(\n    pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:\n     - Cannot find required key 'PopulatedFRU'. Path: '/98'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/99'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/100'.\n     - Cannot find required key 'PopulatedFRU'. Path: '/103'.: Path: '/'>\n\n    The above exception was the direct cause of the following exception:\n\n    Traceback (most recent call last):\n      File \"/usr/lib/python3.9/site-packages/tavern/response/base.py\", line 152, in _maybe_run_validate_functions\n        vf(response)\n      File \"/usr/lib/python3.9/site-packages/tavern/util/extfunctions.py\", line 98, in inner\n        result = func(response, *args, **kwargs)\n      File \"/usr/lib/python3.9/site-packages/tavern/testutils/helpers.py\", line 103, in validate_pykwalify\n        verify_generic(to_verify, schema)\n      File \"/usr/lib/python3.9/site-packages/tavern/schemas/files.py\", line 109, in verify_generic\n        raise BadSchemaError() from e\n    tavern.util.exceptions.BadSchemaError","time":{"start":1674074613589,"stop":1674074614423,"duration":834}}]},"tags":[]},"source":"447edaa04241bee3.json","parameterValues":[]}